"""The carved-wood interface: its art ships, it is used, and it degrades.

The owner asked for "some carved wood style, brown" and "nice images for the
three modes". The pictures are generated by ``tools/generate_ui_art.py`` and
committed under ``assets/ui/``; these checks make sure a build can find them,
that the three mode cards actually show them, and that a missing file makes
the interface plainer rather than broken.
"""

from __future__ import annotations

from types import SimpleNamespace

import pytest
from PyQt5.QtGui import QColor, QFont, QImage, QPainter, QPixmap
from PyQt5.QtWidgets import QLabel

from desktop_bug.app import wood_theme
from desktop_bug.app.mode_menu import MODES, ModeShell
from support import ROOT

ASSETS = ("wood_tile.png", "wood_dark_tile.png", "card_frame.png",
          "mode_companion.png", "mode_adventure.png", "mode_strategy.png",
          "app_icon.png", "app_icon.ico")


def test_the_app_icon_has_every_size_windows_asks_for():
    """The owner: "create an icon for the app itself so that it would show a
    tarantula". Title bar and taskbar use 16-32px, Explorer up to 256."""
    icon = wood_theme.app_icon()
    assert icon is not None and not icon.isNull()
    sizes = {size.width() for size in icon.availableSizes()}
    assert {16, 24, 32, 48, 256} <= sizes, sizes
    spec = (ROOT / "DesktopBugCompanion.spec").read_text(encoding="utf-8")
    assert "icon='assets/ui/app_icon.ico'" in spec


@pytest.fixture(autouse=True, scope="module")
def _qt(qapp):
    """Pixmaps and widgets need the one Qt application object."""


def test_every_asset_is_committed_and_loads():
    for name in ASSETS:
        path = ROOT / "assets" / "ui" / name
        assert path.exists(), f"{name} is missing; run tools/generate_ui_art.py"
        assert not QPixmap(str(path)).isNull(), f"{name} does not load as an image"


def test_the_exe_bundles_the_assets():
    spec = (ROOT / "DesktopBugCompanion.spec").read_text(encoding="utf-8")
    assert "('assets', 'assets')" in spec


def test_the_three_modes_are_named_and_pictured():
    shell = ModeShell(QLabel("editor"), lambda: None)
    assert [title for _, title, _ in MODES] == ["Companion", "Adventure", "Strategy"]
    for kind, _, _ in MODES:
        pixmap = wood_theme.mode_art(kind)
        assert pixmap is not None and pixmap.width() > 200, kind
    pictures = [label for label in shell.home.findChildren(QLabel)
                if label.objectName() == "modeArt"]
    assert len(pictures) == 3
    assert all(label.pixmap() is not None and not label.pixmap().isNull() for label in pictures)


def test_style_sheets_are_well_formed():
    """Qt drops a whole style sheet over one unbalanced brace, silently."""
    for sheet in (wood_theme.shell_qss(), wood_theme.companion_qss(), wood_theme.dialog_qss()):
        assert sheet.count("{") == sheet.count("}")
        assert "url(" in sheet


def test_missing_art_falls_back_to_plain_wood(monkeypatch):
    monkeypatch.setattr(wood_theme, "asset_path", lambda name: None)
    wood_theme.texture.cache_clear()
    try:
        for sheet in (wood_theme.shell_qss(), wood_theme.companion_qss(), wood_theme.dialog_qss()):
            assert "url(" not in sheet
            assert sheet.count("{") == sheet.count("}")
        assert wood_theme.mode_art("companion") is None
        ModeShell(QLabel("editor"), lambda: None)
    finally:
        wood_theme.texture.cache_clear()


def test_the_hud_paints_on_wood():
    from desktop_bug.app.adventure_ui import draw_hud, hud_rect

    spider = SimpleNamespace(
        display_name="Rex", level=3, hp=40.0, max_hp=100.0, energy=20.0, max_energy=100.0,
        attack_cooldown=0.0, _label_font=QFont)
    controller = SimpleNamespace(creature=spider, jump_cooldown=0.0, web_cooldown=1.0,
                                 JUMP_ENERGY=18.0, WEB_ENERGY=12.0)
    window = SimpleNamespace(width=lambda: 600, height=lambda: 200, _adventure_hud_position=None)
    image = QImage(600, 200, QImage.Format_ARGB32_Premultiplied)
    image.fill(QColor(0, 0, 0, 0))
    painter = QPainter(image)
    draw_hud(painter, window, controller)
    painter.end()
    rect = hud_rect(window)
    centre = image.pixelColor(rect.left() + 8, rect.center().y())
    assert centre.alpha() == 255, "the HUD board is not opaque"
    assert centre.red() > centre.blue(), f"the HUD board is not brown: {centre.name()}"
